---
- hosts: crawler
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: install-couchdb
    - role: deploy-harvester

- hosts: masternode
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb-cluster

