- hosts: COMP90024
  
  vars_files:
    - host_vars/config.yaml
    - host_vars/instances.yaml
  gather_facts: true

  roles:
    - role: install-dependencies
    - role: git-clone-source-repository
    - role: mount-volumes
    - role: install-docker

