# Common vars
availability_zone: melbourne-qh2-uom
instance_network: qh2-uom-internal

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-2
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-3
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-4
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data

# Security group
security_groups:
  - name: ccc_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: ccc_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: http_couchdb
    description: "define a HTTP rule for couchdb connection"
    protocol: tcp
    port_range_min: 5984 
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: ccc-1
    volumes: ['vol-1']
  - name: ccc-2
    volumes: ['vol-2']
  - name: ccc-3
    volumes: ['vol-3']
  - name: ccc-4
    volumes: ['vol-4']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: ccc50
instance_flavor: uom.mse.1c4g
wm_inventory_file: "./inventory/wm_inventory_file.ini"
